# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MGModule' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MGModule

  pod 'AFNetworking'
  pod 'MGCategary', :path => '../MGLib/MGCategary'   # ../ pod文件上一个目录

end
